server:
  port: 80

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xm_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 2
      max-active: 30
      min-idle: 2
      max-wait: 1234
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5

  mybatis:
#    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.xiaomi.entity